In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("data/train_age_dataset.csv")
df.head()

,Unnamed: 0,userId,tier,gender,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,...,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2,age_group
0,265153,48958844,2,1,0.0,0.0,0.0,0,0.0,0.0,...,0.200000,0.0,0.041667,0.025000,0.0,0.000000,0.175000,0.033333,0.0,1
1,405231,51100441,2,2,0.0,0.0,0.0,0,0.0,0.0,...,0.093220,0.0,0.012712,0.018644,0.0,0.084746,0.000000,0.033898,82.5,2
2,57867,6887426,2,1,0.0,0.0,0.0,0,0.0,0.0,...,0.002786,0.0,0.000000,0.000557,0.0,0.002786,0.000000,0.000000,0.0,1
3,272618,50742404,2,1,0.0,0.0,0.0,0,0.0,0.0,...,0.008403,0.0,0.000000,0.001681,0.0,0.000000,0.000000,0.008403,0.0,1
4,251123,45589200,2,2,0.0,0.0,0.0,0,0.0,0.0,...,0.204918,0.0,0.000000,0.049180,0.0,0.008197,0.057377,0.180328,0.0,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488877 entries, 0 to 488876
Data columns (total 27 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Unnamed: 0                       488877 non-null  int64
 1   userId                           488877 non-null  int64
 2   tier                             488877 non-null  int64
 3   gender                           488877 non-null  int64
 4   following_rate                   488877 non-null  float64
 5   followers_avg_age                488877 non-null  float64
 6   following_avg_age                488877 non-null  float64
 7   max_repetitive_punc              488877 non-null  int64
 8   num_of_hashtags_per_action       488877 non-null  float64
 9   emoji_count_per_action           488877 non-null  float64
 10  punctuations_per_action          488877 non-null  float64
 11  number_of_words_per_action       488877 non-null  float64
 12  avgCompletion                    488877 non-null  float64
 13  avgTimeSpent                     488877 non-null  float64
 14  avgDuration                      488877 non-null  float64
 15  avgComments                      488877 non-null  int64
 16  creations                        488877 non-null  float64
 17  content_views                    488877 non-null  float64
 18  num_of_comments                  488877 non-null  float64
 19  weekends_trails_watched_per_day  488877 non-null  float64
 20  weekdays_trails_watched_per_day  488877 non-null  float64
 21  slot1_trails_watched_per_day     488877 non-null  float64
 22  slot2_trails_watched_per_day     488877 non-null  float64
 23  slot3_trails_watched_per_day     488877 non-null  float64
 24  slot4_trails_watched_per_day     488877 non-null  float64
 25  avgt2                            488877 non-null  float64
 26  age_group                        488877 non-null  int64
dtypes: float64(20), int64(7)
memory usage: 100.7 MB

In [4]:
df.groupby(["age_group"]).mean()

,Unnamed: 0,userId,tier,gender,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
age_group,,,,,,,,,,,,,,,,,,,,,
1,248739.576693,4.592097e+07,2.000613,1.227803,0.037488,0.156694,0.184691,0.329861,0.000165,0.000715,...,0.005014,0.310092,0.000619,0.052511,0.050980,0.020637,0.112356,0.113405,0.113526,45.525977
2,289442.839609,3.045253e+07,1.942718,1.197321,0.135835,0.610343,0.710808,1.503648,0.000780,0.002701,...,0.028927,0.291763,0.002946,0.088530,0.043408,0.027394,0.119307,0.123351,0.124048,334.597225
3,313573.984918,3.647262e+07,1.928266,1.155569,0.157764,0.702247,0.813775,1.434922,0.000513,0.001080,...,0.034721,0.519671,0.004372,0.096760,0.096291,0.051534,0.191694,0.201938,0.229808,401.498253
4,328450.442478,4.178363e+07,1.926139,1.210598,0.181761,0.706179,0.801821,1.381856,0.000118,0.000556,...,0.049054,0.770412,0.005793,0.149007,0.141578,0.081579,0.262730,0.313203,0.348394,368.431505

In [5]:
df["age_group"].value_counts()

1    308315
4     60803
3     60404
2     59355
Name: age_group, dtype: int64

In [6]:
df.shape

(488877, 27)

#### Making a copy and preserving original data set in df:

In [7]:
df1 = df.copy()

#### Dropping UserId column:

In [8]:
df1.drop(["userId"], axis=1, inplace= True)

In [9]:
df1.head()

,Unnamed: 0,tier,gender,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,punctuations_per_action,...,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2,age_group
0,265153,2,1,0.0,0.0,0.0,0,0.0,0.0,0.000000,...,0.200000,0.0,0.041667,0.025000,0.0,0.000000,0.175000,0.033333,0.0,1
1,405231,2,2,0.0,0.0,0.0,0,0.0,0.0,0.076923,...,0.093220,0.0,0.012712,0.018644,0.0,0.084746,0.000000,0.033898,82.5,2
2,57867,2,1,0.0,0.0,0.0,0,0.0,0.0,0.000000,...,0.002786,0.0,0.000000,0.000557,0.0,0.002786,0.000000,0.000000,0.0,1
3,272618,2,1,0.0,0.0,0.0,0,0.0,0.0,0.000000,...,0.008403,0.0,0.000000,0.001681,0.0,0.000000,0.000000,0.008403,0.0,1
4,251123,2,2,0.0,0.0,0.0,0,0.0,0.0,0.000000,...,0.204918,0.0,0.000000,0.049180,0.0,0.008197,0.057377,0.180328,0.0,1

### Dealing with categorical variables:

In [10]:
df_cat = df1[["gender", "tier", "age_group"]]

In [11]:
df_cat['gender'] = df_cat['gender'].map({1:1, 2:0}).astype('uint8')

C:\Users\Admin\anaconda3.2020\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [12]:
df_cat["tier"].value_counts()

2    397890
1     51511
3     39476
Name: tier, dtype: int64

In [13]:
df2 = pd.get_dummies(df_cat["tier"])
df2.columns = ["tier_1","tier_2","tier_3"]
df2.head()

   tier_1  tier_2  tier_3
0       0       1       0
1       0       1       0
2       0       1       0
3       0       1       0
4       0       1       0

In [14]:
df_cat = pd.concat([df_cat.drop(["tier"], axis=1),df2], axis=1)

In [15]:
df_cat.head()

   gender  age_group  tier_1  tier_2  tier_3
0       1          1       0       1       0
1       0          2       0       1       0
2       1          1       0       1       0
3       1          1       0       1       0
4       0          1       0       1       0

### Dealing with numeric variables:

In [16]:
df_num = df1.drop(["tier","gender","age_group"], axis=1)
df_num.head()

,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,punctuations_per_action,number_of_words_per_action,avgCompletion,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
0,265153,0.0,0.0,0.0,0,0.0,0.0,0.000000,0.000000,0.463330,...,0.000000,0.200000,0.0,0.041667,0.025000,0.0,0.000000,0.175000,0.033333,0.0
1,405231,0.0,0.0,0.0,0,0.0,0.0,0.076923,0.153846,0.429468,...,0.008475,0.093220,0.0,0.012712,0.018644,0.0,0.084746,0.000000,0.033898,82.5
2,57867,0.0,0.0,0.0,0,0.0,0.0,0.000000,0.000000,0.341657,...,0.000000,0.002786,0.0,0.000000,0.000557,0.0,0.002786,0.000000,0.000000,0.0
3,272618,0.0,0.0,0.0,0,0.0,0.0,0.000000,0.000000,0.005735,...,0.000000,0.008403,0.0,0.000000,0.001681,0.0,0.000000,0.000000,0.008403,0.0
4,251123,0.0,0.0,0.0,0,0.0,0.0,0.000000,0.000000,0.456549,...,0.000000,0.204918,0.0,0.000000,0.049180,0.0,0.008197,0.057377,0.180328,0.0

In [17]:
Std = df_num.std()
Mean = df_num.mean()
df_num = (df_num - Mean)/Std

In [18]:
df_num.describe()

,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,punctuations_per_action,number_of_words_per_action,avgCompletion,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
count,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,...,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05
mean,-9.418105e-17,-3.295374e-15,3.666243e-15,7.113034e-15,-2.521574e-16,-9.279987e-15,2.392272e-15,4.343597e-15,5.851335e-14,9.872523e-14,...,4.216185e-14,-8.204251e-14,6.536793e-15,-1.558692e-14,8.768067e-14,-3.645395e-15,1.758861e-14,1.390724e-14,-6.410091e-15,-9.870548e-16
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-1.732091e+00,-3.332267e-02,-4.257077e-01,-4.355915e-01,-2.404940e-01,-2.268127e-02,-4.815076e-02,-8.025581e-02,-2.766381e-01,-1.744404e+00,...,-9.459493e-02,-4.309335e-01,-6.572489e-02,-3.522254e-01,-3.828987e-01,-1.693876e-01,-3.519645e-01,-3.327462e-01,-3.154612e-01,-1.677878e-01
25%,-8.661986e-01,-3.332267e-02,-4.257077e-01,-4.355915e-01,-2.404940e-01,-2.268127e-02,-4.815076e-02,-8.025581e-02,-2.766381e-01,-7.260816e-01,...,-9.459493e-02,-3.870111e-01,-6.572489e-02,-3.522254e-01,-3.699382e-01,-1.693876e-01,-3.519645e-01,-3.327462e-01,-3.154612e-01,-1.677878e-01
50%,-2.932362e-04,-3.332267e-02,-4.257077e-01,-4.355915e-01,-2.404940e-01,-2.268127e-02,-4.815076e-02,-8.025581e-02,-2.766381e-01,-6.057618e-02,...,-9.459493e-02,-2.949087e-01,-6.572489e-02,-3.334269e-01,-2.920873e-01,-1.693876e-01,-3.225706e-01,-3.005268e-01,-2.838458e-01,-1.677878e-01
75%,8.661860e-01,-2.982938e-02,-4.257077e-01,-4.355915e-01,-2.404940e-01,-2.268127e-02,-4.815076e-02,-8.025581e-02,-4.472669e-02,6.084163e-01,...,-4.420256e-02,-2.930169e-02,-6.572489e-02,-6.799223e-02,-4.525877e-02,-1.693876e-01,-6.089662e-02,-7.025862e-02,-7.167649e-02,1.415585e-02
max,1.731989e+00,3.627638e+02,4.474247e+00,3.887373e+00,2.026234e+02,1.909009e+02,1.471449e+02,1.712314e+02,4.053308e+02,3.368876e+00,...,3.512802e+02,8.314479e+01,2.681486e+02,8.113625e+01,1.069233e+02,1.009481e+02,6.896033e+01,9.940940e+01,1.095385e+02,3.985711e+01

### Combining the Categorical and Numeric parts

In [19]:
df_comb = pd.concat([df_cat, df_num], axis=1)
df_comb.head()

,gender,age_group,tier_1,tier_2,tier_3,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
0,1,1,0,1,0,-0.041152,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,-0.210993,-0.065725,-0.154841,-0.239871,-0.169388,-0.351964,0.054423,-0.249069,-0.167788
1,0,2,0,1,0,0.852156,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.047619,-0.328942,-0.065725,-0.292006,-0.276234,-0.169388,-0.141475,-0.332746,-0.247943,-0.083775
2,1,1,0,1,0,-1.363061,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,-0.428837,-0.065725,-0.352225,-0.379711,-0.169388,-0.345046,-0.332746,-0.315461,-0.167788
3,1,1,0,1,0,0.006454,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,-0.422631,-0.065725,-0.352225,-0.373283,-0.169388,-0.351964,-0.332746,-0.298724,-0.167788
4,0,1,0,1,0,-0.130624,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,-0.205561,-0.065725,-0.352225,-0.101532,-0.169388,-0.331606,-0.205805,0.043711,-0.167788

### Shuffling the data:

In [20]:
df_shuffled = df_comb.iloc[np.random.permutation(range(len(df_comb)))]

In [21]:
df_shuffled.reset_index(drop=True, inplace=True)
df_shuffled.head()

,gender,age_group,tier_1,tier_2,tier_3,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
0,1,1,0,1,0,0.446724,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,-0.291894,-0.065725,-0.352225,-0.237856,-0.169388,-0.351964,-0.332746,-0.062983,-0.167788
1,1,4,0,1,0,1.437483,0.052183,3.074260,1.725891,-0.240494,...,-0.043740,-0.087359,1.135069,-0.352225,0.037000,-0.169388,0.536727,-0.312449,-0.315461,-0.084623
2,1,1,0,1,0,-0.254202,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,-0.414097,-0.065725,-0.314022,-0.382899,-0.169388,-0.351964,-0.332746,-0.283336,-0.167788
3,0,1,0,1,0,0.415068,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,1.893564,-0.065725,1.798223,1.378604,-0.169388,1.380145,0.569678,2.357708,-0.167788
4,1,4,0,1,0,0.776930,-0.029388,2.024269,2.266261,-0.240494,...,-0.071530,-0.407401,-0.065725,-0.352225,-0.362268,-0.169388,-0.351964,-0.308198,-0.301649,16.203070

### Separating the output:

In [22]:
df_y = df_shuffled[["age_group"]]

In [23]:
df_shuffled.drop(["age_group"], axis=1, inplace= True)

C:\Users\Admin\anaconda3.2020\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [24]:
df_shuffled.head()

,gender,tier_1,tier_2,tier_3,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
0,1,0,1,0,0.446724,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.094595,-0.291894,-0.065725,-0.352225,-0.237856,-0.169388,-0.351964,-0.332746,-0.062983,-0.167788
1,1,0,1,0,1.437483,0.052183,3.074260,1.725891,-0.240494,-0.022681,...,-0.043740,-0.087359,1.135069,-0.352225,0.037000,-0.169388,0.536727,-0.312449,-0.315461,-0.084623
2,1,0,1,0,-0.254202,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.094595,-0.414097,-0.065725,-0.314022,-0.382899,-0.169388,-0.351964,-0.332746,-0.283336,-0.167788
3,0,0,1,0,0.415068,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.094595,1.893564,-0.065725,1.798223,1.378604,-0.169388,1.380145,0.569678,2.357708,-0.167788
4,1,0,1,0,0.776930,-0.029388,2.024269,2.266261,-0.240494,-0.022681,...,-0.071530,-0.407401,-0.065725,-0.352225,-0.362268,-0.169388,-0.351964,-0.308198,-0.301649,16.203070

In [25]:
df_y.head()

   age_group
0          1
1          4
2          1
3          1
4          4

#### Current relevant variables in memory:

Dataframes:
- df --> untouched dataset
- df_comb --> normalized dataset 
- df_shuffled --> shuffled dataset
- df_y --> output

Transformation:
- Std --> standard deviation of dataset
- Mean --> mean of dataset

### Converting data into numpy arrays and splitting into training and validation sets:

In [26]:
X = df_shuffled.to_numpy()
y = pd.get_dummies(df_y["age_group"]).to_numpy()

In [27]:
X.shape, y.shape

((488877, 27), (488877, 4))

In [28]:
X[0], y[:4]

(array([ 1.        ,  0.        ,  1.        ,  0.        ,  0.44672438,
        -0.03332267, -0.42570773, -0.4355915 , -0.24049399, -0.02268127,
        -0.04815076, -0.08025581, -0.27663815,  0.86618876, -0.00175702,
        -0.88922057, -0.0419517 , -0.09459493, -0.29189366, -0.06572489,
        -0.35222535, -0.2378562 , -0.16938762, -0.35196446, -0.33274616,
        -0.06298294, -0.16778783]),
 array([[1, 0, 0, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [1, 0, 0, 0]], dtype=uint8))

In [29]:
# Keeping 40,000 examples in validation set and remaining in training set
X_train = X[:-40000]
X_val = X[-40000:]
y_train = y[:-40000]
y_val = y[-40000:]

### Using keras to build a multi-class classifier

In [32]:
!pip install --upgrade pip
!pip install tensorflow

Collecting pip
  Downloading pip-20.3.1-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2

ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-uninstall-pwh17tij\\pip.exe'
Consider using the `--user` option or check the permissions.

Collecting tensorflow
  Using cached tensorflow-2.3.1-cp37-cp37m-win_amd64.whl (342.5 MB)
Requirement already satisfied: wrapt>=1.11.1 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.11.2)
Requirement already satisfied: wheel>=0.26 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (0.34.2)
Requirement already satisfied: h5py<2.11.0,>=2.10.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (2.10.0)
Requirement already satisfied: numpy<1.19.0,>=1.16.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.18.1)
Requirement already satisfied: six>=1.12.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.14.0)
Collecting absl-py>=0.7.0
  Downloading absl_py-0.11.0-py3-none-any.whl (127 kB)
Requirement already satisfied: six>=1.12.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.14.0)
Collecting astunparse==1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: wheel>=0.26 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (0.34.2)
Requirement already satisfied: six>=1.12.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.14.0)
Collecting gast==0.3.3
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
Collecting google-pasta>=0.1.8
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Requirement already satisfied: six>=1.12.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.14.0)
Collecting grpcio>=1.8.6
  Using cached grpcio-1.34.0-cp37-cp37m-win_amd64.whl (2.9 MB)
Requirement already satisfied: six>=1.12.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.14.0)
Requirement already satisfied: numpy<1.19.0,>=1.16.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.18.1)
Requirement already satisfied: six>=1.12.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.14.0)
Collecting keras-preprocessing<1.2,>=1.1.1
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Requirement already satisfied: six>=1.12.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.14.0)
Requirement already satisfied: numpy<1.19.0,>=1.16.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.18.1)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Requirement already satisfied: numpy<1.19.0,>=1.16.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.18.1)
Collecting protobuf>=3.9.2
  Using cached protobuf-3.14.0-cp37-cp37m-win_amd64.whl (798 kB)
Requirement already satisfied: six>=1.12.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.14.0)
Collecting tensorboard<3,>=2.3.0
  Using cached tensorboard-2.4.0-py3-none-any.whl (10.6 MB)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow) (2.22.0)
Requirement already satisfied: six>=1.12.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.14.0)
Requirement already satisfied: numpy<1.19.0,>=1.16.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.18.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow) (45.2.0.post20200210)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow) (1.0.0)
Requirement already satisfied: wheel>=0.26 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (0.34.2)
Collecting google-auth<2,>=1.6.3
  Downloading google_auth-1.23.0-py2.py3-none-any.whl (114 kB)
Requirement already satisfied: six>=1.12.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorflow) (1.14.0)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow) (45.2.0.post20200210)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.2-py2.py3-none-any.whl (18 kB)
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.3-py3-none-any.whl (96 kB)
Requirement already satisfied: importlib-metadata in c:\users\admin\anaconda3.2020\lib\site-packages (from markdown>=2.6.8->tensorboard<3,>=2.3.0->tensorflow) (1.5.0)
Requirement already satisfied: zipp>=0.5 in c:\users\admin\anaconda3.2020\lib\site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<3,>=2.3.0->tensorflow) (2.2.0)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\admin\anaconda3.2020\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\admin\anaconda3.2020\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\admin\anaconda3.2020\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3.2020\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow) (2019.11.28)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\admin\anaconda3.2020\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow) (2.22.0)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.6-py3-none-any.whl (47 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.7.0-py3-none-any.whl (779 kB)
Collecting tensorflow-estimator<2.4.0,>=2.3.0
  Using cached tensorflow_estimator-2.3.0-py2.py3-none-any.whl (459 kB)
Collecting termcolor>=1.1.0
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
Building wheels for collected packages: termcolor
  Building wheel for termcolor (setup.py): started
  Building wheel for termcolor (setup.py): finished with status 'done'
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4835 sha256=1e7c569c5adf6108d7ee31c001ffa01e35ea324dd22ff1674ea647b056d281d9
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\3f\e3\ec\8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2
Successfully built termcolor
Installing collected packages: pyasn1, rsa, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, google-auth, tensorboard-plugin-wit, protobuf, markdown, grpcio, google-auth-oauthlib, absl-py, termcolor, tensorflow-estimator, tensorboard, opt-einsum, keras-preprocessing, google-pasta, gast, astunparse, tensorflow
Successfully installed absl-py-0.11.0 astunparse-1.6.3 cachetools-4.1.1 gast-0.3.3 google-auth-1.23.0 google-auth-oauthlib-0.4.2 google-pasta-0.2.0 grpcio-1.34.0 keras-preprocessing-1.1.2 markdown-3.3.3 oauthlib-3.1.0 opt-einsum-3.3.0 protobuf-3.14.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-oauthlib-1.3.0 rsa-4.6 tensorboard-2.4.0 tensorboard-plugin-wit-1.7.0 tensorflow-2.3.1 tensorflow-estimator-2.3.0 termcolor-1.1.0

In [33]:
import tensorflow as tf
from tensorflow import keras