In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [15]:
df = pd.read_csv("data/train_age_dataset.csv")
df.head()

,Unnamed: 0,userId,tier,gender,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,...,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2,age_group
0,265153,48958844,2,1,0.0,0.0,0.0,0,0.0,0.0,...,0.200000,0.0,0.041667,0.025000,0.0,0.000000,0.175000,0.033333,0.0,1
1,405231,51100441,2,2,0.0,0.0,0.0,0,0.0,0.0,...,0.093220,0.0,0.012712,0.018644,0.0,0.084746,0.000000,0.033898,82.5,2
2,57867,6887426,2,1,0.0,0.0,0.0,0,0.0,0.0,...,0.002786,0.0,0.000000,0.000557,0.0,0.002786,0.000000,0.000000,0.0,1
3,272618,50742404,2,1,0.0,0.0,0.0,0,0.0,0.0,...,0.008403,0.0,0.000000,0.001681,0.0,0.000000,0.000000,0.008403,0.0,1
4,251123,45589200,2,2,0.0,0.0,0.0,0,0.0,0.0,...,0.204918,0.0,0.000000,0.049180,0.0,0.008197,0.057377,0.180328,0.0,1

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488877 entries, 0 to 488876
Data columns (total 27 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Unnamed: 0                       488877 non-null  int64
 1   userId                           488877 non-null  int64
 2   tier                             488877 non-null  int64
 3   gender                           488877 non-null  int64
 4   following_rate                   488877 non-null  float64
 5   followers_avg_age                488877 non-null  float64
 6   following_avg_age                488877 non-null  float64
 7   max_repetitive_punc              488877 non-null  int64
 8   num_of_hashtags_per_action       488877 non-null  float64
 9   emoji_count_per_action           488877 non-null  float64
 10  punctuations_per_action          488877 non-null  float64
 11  number_of_words_per_action       488877 non-null  float64
 12  avgCompletion                    488877 non-null  float64
 13  avgTimeSpent                     488877 non-null  float64
 14  avgDuration                      488877 non-null  float64
 15  avgComments                      488877 non-null  int64
 16  creations                        488877 non-null  float64
 17  content_views                    488877 non-null  float64
 18  num_of_comments                  488877 non-null  float64
 19  weekends_trails_watched_per_day  488877 non-null  float64
 20  weekdays_trails_watched_per_day  488877 non-null  float64
 21  slot1_trails_watched_per_day     488877 non-null  float64
 22  slot2_trails_watched_per_day     488877 non-null  float64
 23  slot3_trails_watched_per_day     488877 non-null  float64
 24  slot4_trails_watched_per_day     488877 non-null  float64
 25  avgt2                            488877 non-null  float64
 26  age_group                        488877 non-null  int64
dtypes: float64(20), int64(7)
memory usage: 100.7 MB

In [17]:
df.groupby(["age_group"]).mean()

,Unnamed: 0,userId,tier,gender,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
age_group,,,,,,,,,,,,,,,,,,,,,
1,248739.576693,4.592097e+07,2.000613,1.227803,0.037488,0.156694,0.184691,0.329861,0.000165,0.000715,...,0.005014,0.310092,0.000619,0.052511,0.050980,0.020637,0.112356,0.113405,0.113526,45.525977
2,289442.839609,3.045253e+07,1.942718,1.197321,0.135835,0.610343,0.710808,1.503648,0.000780,0.002701,...,0.028927,0.291763,0.002946,0.088530,0.043408,0.027394,0.119307,0.123351,0.124048,334.597225
3,313573.984918,3.647262e+07,1.928266,1.155569,0.157764,0.702247,0.813775,1.434922,0.000513,0.001080,...,0.034721,0.519671,0.004372,0.096760,0.096291,0.051534,0.191694,0.201938,0.229808,401.498253
4,328450.442478,4.178363e+07,1.926139,1.210598,0.181761,0.706179,0.801821,1.381856,0.000118,0.000556,...,0.049054,0.770412,0.005793,0.149007,0.141578,0.081579,0.262730,0.313203,0.348394,368.431505

In [27]:
df["age_group"].value_counts()

1    308315
4     60803
3     60404
2     59355
Name: age_group, dtype: int64

In [56]:
df.shape

(488877, 27)

#### Making a copy and preserving original data set in df:

In [37]:
df1 = df.copy()

#### Dropping UserId column:

In [38]:
df1.drop(["userId"], axis=1, inplace= True)

In [39]:
df1.head()

,Unnamed: 0,tier,gender,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,punctuations_per_action,...,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2,age_group
0,265153,2,1,0.0,0.0,0.0,0,0.0,0.0,0.000000,...,0.200000,0.0,0.041667,0.025000,0.0,0.000000,0.175000,0.033333,0.0,1
1,405231,2,2,0.0,0.0,0.0,0,0.0,0.0,0.076923,...,0.093220,0.0,0.012712,0.018644,0.0,0.084746,0.000000,0.033898,82.5,2
2,57867,2,1,0.0,0.0,0.0,0,0.0,0.0,0.000000,...,0.002786,0.0,0.000000,0.000557,0.0,0.002786,0.000000,0.000000,0.0,1
3,272618,2,1,0.0,0.0,0.0,0,0.0,0.0,0.000000,...,0.008403,0.0,0.000000,0.001681,0.0,0.000000,0.000000,0.008403,0.0,1
4,251123,2,2,0.0,0.0,0.0,0,0.0,0.0,0.000000,...,0.204918,0.0,0.000000,0.049180,0.0,0.008197,0.057377,0.180328,0.0,1

### Dealing with categorical variables:

In [40]:
df_cat = df1[["gender", "tier"]]

In [41]:
df_cat['gender'] = df_cat['gender'].map({1:1, 2:0}).astype('uint8')

C:\Users\Admin\anaconda3.2020\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [36]:
df_cat["tier"].value_counts()

2    397890
1     51511
3     39476
Name: tier, dtype: int64

In [42]:
df2 = pd.get_dummies(df_cat["tier"])
df2.columns = ["tier_1","tier_2","tier_3"]
df2.head()

   tier_1  tier_2  tier_3
0       0       1       0
1       0       1       0
2       0       1       0
3       0       1       0
4       0       1       0

In [43]:
df_cat = pd.concat([df_cat.drop(["tier"], axis=1),df2], axis=1)

In [44]:
df_cat.head()

   gender  tier_1  tier_2  tier_3
0       1       0       1       0
1       0       0       1       0
2       1       0       1       0
3       1       0       1       0
4       0       0       1       0

### Dealing with numeric variables:

In [49]:
df_num = df1.drop(["tier","gender"], axis=1)
df_num.head()

,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,punctuations_per_action,number_of_words_per_action,avgCompletion,...,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2,age_group
0,265153,0.0,0.0,0.0,0,0.0,0.0,0.000000,0.000000,0.463330,...,0.200000,0.0,0.041667,0.025000,0.0,0.000000,0.175000,0.033333,0.0,1
1,405231,0.0,0.0,0.0,0,0.0,0.0,0.076923,0.153846,0.429468,...,0.093220,0.0,0.012712,0.018644,0.0,0.084746,0.000000,0.033898,82.5,2
2,57867,0.0,0.0,0.0,0,0.0,0.0,0.000000,0.000000,0.341657,...,0.002786,0.0,0.000000,0.000557,0.0,0.002786,0.000000,0.000000,0.0,1
3,272618,0.0,0.0,0.0,0,0.0,0.0,0.000000,0.000000,0.005735,...,0.008403,0.0,0.000000,0.001681,0.0,0.000000,0.000000,0.008403,0.0,1
4,251123,0.0,0.0,0.0,0,0.0,0.0,0.000000,0.000000,0.456549,...,0.204918,0.0,0.000000,0.049180,0.0,0.008197,0.057377,0.180328,0.0,1

In [50]:
df_num.describe()

,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,punctuations_per_action,number_of_words_per_action,avgCompletion,...,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2,age_group
count,488877.000000,488877.000000,488877.000000,488877.000000,488877.000000,488877.000000,488877.000000,488877.000000,488877.000000,488877.000000,...,488877.000000,488877.000000,488877.000000,488877.000000,488877.000000,488877.000000,488877.000000,488877.000000,488877.000000,488877.000000
mean,271605.981815,0.082233,0.347520,0.403049,0.739748,0.000277,0.000981,0.012805,0.179148,0.341582,...,0.391013,0.002009,0.074353,0.066927,0.032855,0.141705,0.150401,0.158382,164.765782,1.741643
std,156808.138002,2.467781,0.816334,0.925291,3.075954,0.012221,0.020381,0.159553,0.647588,0.195441,...,0.905303,0.030561,0.211094,0.174791,0.193962,0.402612,0.451999,0.502065,981.988886,1.088559
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000653,...,0.000887,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,135779.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.199675,...,0.040650,0.000000,0.000000,0.002265,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,271560.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.329743,...,0.124031,0.000000,0.003968,0.015873,0.000000,0.011834,0.014563,0.015873,0.000000,1.000000
75%,407431.000000,0.008621,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.150183,0.460492,...,0.364486,0.000000,0.060000,0.059016,0.000000,0.117188,0.118644,0.122396,178.666667,2.000000
max,543196.000000,895.304000,4.000000,4.000000,624.000000,2.333333,3.000000,27.333333,262.666667,1.000000,...,75.662281,8.196850,17.201754,18.756140,19.612903,27.905983,45.083333,55.153846,39304.000000,4.000000

In [51]:
Std = df_num.std()
Mean = df_num.mean()
df_num = (df_num - Mean)/Std

In [52]:
df_num.describe()

,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,punctuations_per_action,number_of_words_per_action,avgCompletion,...,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2,age_group
count,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,...,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05
mean,-9.418105e-17,-3.295374e-15,3.666243e-15,7.113034e-15,-2.521574e-16,-9.279987e-15,2.392272e-15,4.343597e-15,5.851335e-14,9.872523e-14,...,-8.204251e-14,6.536793e-15,-1.558692e-14,8.768067e-14,-3.645395e-15,1.758861e-14,1.390724e-14,-6.410091e-15,-9.870548e-16,-1.615172e-15
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-1.732091e+00,-3.332267e-02,-4.257077e-01,-4.355915e-01,-2.404940e-01,-2.268127e-02,-4.815076e-02,-8.025581e-02,-2.766381e-01,-1.744404e+00,...,-4.309335e-01,-6.572489e-02,-3.522254e-01,-3.828987e-01,-1.693876e-01,-3.519645e-01,-3.327462e-01,-3.154612e-01,-1.677878e-01,-6.813065e-01
25%,-8.661986e-01,-3.332267e-02,-4.257077e-01,-4.355915e-01,-2.404940e-01,-2.268127e-02,-4.815076e-02,-8.025581e-02,-2.766381e-01,-7.260816e-01,...,-3.870111e-01,-6.572489e-02,-3.522254e-01,-3.699382e-01,-1.693876e-01,-3.519645e-01,-3.327462e-01,-3.154612e-01,-1.677878e-01,-6.813065e-01
50%,-2.932362e-04,-3.332267e-02,-4.257077e-01,-4.355915e-01,-2.404940e-01,-2.268127e-02,-4.815076e-02,-8.025581e-02,-2.766381e-01,-6.057618e-02,...,-2.949087e-01,-6.572489e-02,-3.334269e-01,-2.920873e-01,-1.693876e-01,-3.225706e-01,-3.005268e-01,-2.838458e-01,-1.677878e-01,-6.813065e-01
75%,8.661860e-01,-2.982938e-02,-4.257077e-01,-4.355915e-01,-2.404940e-01,-2.268127e-02,-4.815076e-02,-8.025581e-02,-4.472669e-02,6.084163e-01,...,-2.930169e-02,-6.572489e-02,-6.799223e-02,-4.525877e-02,-1.693876e-01,-6.089662e-02,-7.025862e-02,-7.167649e-02,1.415585e-02,2.373389e-01
max,1.731989e+00,3.627638e+02,4.474247e+00,3.887373e+00,2.026234e+02,1.909009e+02,1.471449e+02,1.712314e+02,4.053308e+02,3.368876e+00,...,8.314479e+01,2.681486e+02,8.113625e+01,1.069233e+02,1.009481e+02,6.896033e+01,9.940940e+01,1.095385e+02,3.985711e+01,2.074630e+00

### Combining the Categorical and numeric parts

In [53]:
df_comb = pd.concat([df_cat, df_num], axis=1)
df_comb.head()

,gender,tier_1,tier_2,tier_3,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,...,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2,age_group
0,1,0,1,0,-0.041152,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.210993,-0.065725,-0.154841,-0.239871,-0.169388,-0.351964,0.054423,-0.249069,-0.167788,-0.681307
1,0,0,1,0,0.852156,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.328942,-0.065725,-0.292006,-0.276234,-0.169388,-0.141475,-0.332746,-0.247943,-0.083775,0.237339
2,1,0,1,0,-1.363061,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.428837,-0.065725,-0.352225,-0.379711,-0.169388,-0.345046,-0.332746,-0.315461,-0.167788,-0.681307
3,1,0,1,0,0.006454,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.422631,-0.065725,-0.352225,-0.373283,-0.169388,-0.351964,-0.332746,-0.298724,-0.167788,-0.681307
4,0,0,1,0,-0.130624,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.205561,-0.065725,-0.352225,-0.101532,-0.169388,-0.331606,-0.205805,0.043711,-0.167788,-0.681307

In [55]:
df_comb.to_numpy().shape

(488877, 28)