In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("data/train_age_dataset.csv")
df.head()

,Unnamed: 0,userId,tier,gender,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,...,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2,age_group
0,265153,48958844,2,1,0.0,0.0,0.0,0,0.0,0.0,...,0.200000,0.0,0.041667,0.025000,0.0,0.000000,0.175000,0.033333,0.0,1
1,405231,51100441,2,2,0.0,0.0,0.0,0,0.0,0.0,...,0.093220,0.0,0.012712,0.018644,0.0,0.084746,0.000000,0.033898,82.5,2
2,57867,6887426,2,1,0.0,0.0,0.0,0,0.0,0.0,...,0.002786,0.0,0.000000,0.000557,0.0,0.002786,0.000000,0.000000,0.0,1
3,272618,50742404,2,1,0.0,0.0,0.0,0,0.0,0.0,...,0.008403,0.0,0.000000,0.001681,0.0,0.000000,0.000000,0.008403,0.0,1
4,251123,45589200,2,2,0.0,0.0,0.0,0,0.0,0.0,...,0.204918,0.0,0.000000,0.049180,0.0,0.008197,0.057377,0.180328,0.0,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488877 entries, 0 to 488876
Data columns (total 27 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Unnamed: 0                       488877 non-null  int64
 1   userId                           488877 non-null  int64
 2   tier                             488877 non-null  int64
 3   gender                           488877 non-null  int64
 4   following_rate                   488877 non-null  float64
 5   followers_avg_age                488877 non-null  float64
 6   following_avg_age                488877 non-null  float64
 7   max_repetitive_punc              488877 non-null  int64
 8   num_of_hashtags_per_action       488877 non-null  float64
 9   emoji_count_per_action           488877 non-null  float64
 10  punctuations_per_action          488877 non-null  float64
 11  number_of_words_per_action       488877 non-null  float64
 12  avgCompletion                    488877 non-null  float64
 13  avgTimeSpent                     488877 non-null  float64
 14  avgDuration                      488877 non-null  float64
 15  avgComments                      488877 non-null  int64
 16  creations                        488877 non-null  float64
 17  content_views                    488877 non-null  float64
 18  num_of_comments                  488877 non-null  float64
 19  weekends_trails_watched_per_day  488877 non-null  float64
 20  weekdays_trails_watched_per_day  488877 non-null  float64
 21  slot1_trails_watched_per_day     488877 non-null  float64
 22  slot2_trails_watched_per_day     488877 non-null  float64
 23  slot3_trails_watched_per_day     488877 non-null  float64
 24  slot4_trails_watched_per_day     488877 non-null  float64
 25  avgt2                            488877 non-null  float64
 26  age_group                        488877 non-null  int64
dtypes: float64(20), int64(7)
memory usage: 100.7 MB

In [4]:
df.groupby(["age_group"]).mean()

,Unnamed: 0,userId,tier,gender,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
age_group,,,,,,,,,,,,,,,,,,,,,
1,248739.576693,4.592097e+07,2.000613,1.227803,0.037488,0.156694,0.184691,0.329861,0.000165,0.000715,...,0.005014,0.310092,0.000619,0.052511,0.050980,0.020637,0.112356,0.113405,0.113526,45.525977
2,289442.839609,3.045253e+07,1.942718,1.197321,0.135835,0.610343,0.710808,1.503648,0.000780,0.002701,...,0.028927,0.291763,0.002946,0.088530,0.043408,0.027394,0.119307,0.123351,0.124048,334.597225
3,313573.984918,3.647262e+07,1.928266,1.155569,0.157764,0.702247,0.813775,1.434922,0.000513,0.001080,...,0.034721,0.519671,0.004372,0.096760,0.096291,0.051534,0.191694,0.201938,0.229808,401.498253
4,328450.442478,4.178363e+07,1.926139,1.210598,0.181761,0.706179,0.801821,1.381856,0.000118,0.000556,...,0.049054,0.770412,0.005793,0.149007,0.141578,0.081579,0.262730,0.313203,0.348394,368.431505

In [5]:
df["age_group"].value_counts()

1    308315
4     60803
3     60404
2     59355
Name: age_group, dtype: int64

In [6]:
df.shape

(488877, 27)

#### Making a copy and preserving original data set in df:

In [7]:
df1 = df.copy()

#### Dropping UserId column:

In [8]:
df1.drop(["userId"], axis=1, inplace= True)

In [9]:
df1.head()

,Unnamed: 0,tier,gender,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,punctuations_per_action,...,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2,age_group
0,265153,2,1,0.0,0.0,0.0,0,0.0,0.0,0.000000,...,0.200000,0.0,0.041667,0.025000,0.0,0.000000,0.175000,0.033333,0.0,1
1,405231,2,2,0.0,0.0,0.0,0,0.0,0.0,0.076923,...,0.093220,0.0,0.012712,0.018644,0.0,0.084746,0.000000,0.033898,82.5,2
2,57867,2,1,0.0,0.0,0.0,0,0.0,0.0,0.000000,...,0.002786,0.0,0.000000,0.000557,0.0,0.002786,0.000000,0.000000,0.0,1
3,272618,2,1,0.0,0.0,0.0,0,0.0,0.0,0.000000,...,0.008403,0.0,0.000000,0.001681,0.0,0.000000,0.000000,0.008403,0.0,1
4,251123,2,2,0.0,0.0,0.0,0,0.0,0.0,0.000000,...,0.204918,0.0,0.000000,0.049180,0.0,0.008197,0.057377,0.180328,0.0,1

### Dealing with categorical variables:

In [10]:
df_cat = df1[["gender", "tier", "age_group"]]

In [11]:
df_cat['gender'] = df_cat['gender'].map({1:1, 2:0}).astype('uint8')

C:\Users\Admin\anaconda3.2020\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [12]:
df_cat["tier"].value_counts()

2    397890
1     51511
3     39476
Name: tier, dtype: int64

In [13]:
df2 = pd.get_dummies(df_cat["tier"])
df2.columns = ["tier_1","tier_2","tier_3"]
df2.head()

   tier_1  tier_2  tier_3
0       0       1       0
1       0       1       0
2       0       1       0
3       0       1       0
4       0       1       0

In [14]:
df_cat = pd.concat([df_cat.drop(["tier"], axis=1),df2], axis=1)

In [15]:
df_cat.head()

   gender  age_group  tier_1  tier_2  tier_3
0       1          1       0       1       0
1       0          2       0       1       0
2       1          1       0       1       0
3       1          1       0       1       0
4       0          1       0       1       0

### Dealing with numeric variables:

In [16]:
df_num = df1.drop(["tier","gender","age_group"], axis=1)
df_num.head()

,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,punctuations_per_action,number_of_words_per_action,avgCompletion,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
0,265153,0.0,0.0,0.0,0,0.0,0.0,0.000000,0.000000,0.463330,...,0.000000,0.200000,0.0,0.041667,0.025000,0.0,0.000000,0.175000,0.033333,0.0
1,405231,0.0,0.0,0.0,0,0.0,0.0,0.076923,0.153846,0.429468,...,0.008475,0.093220,0.0,0.012712,0.018644,0.0,0.084746,0.000000,0.033898,82.5
2,57867,0.0,0.0,0.0,0,0.0,0.0,0.000000,0.000000,0.341657,...,0.000000,0.002786,0.0,0.000000,0.000557,0.0,0.002786,0.000000,0.000000,0.0
3,272618,0.0,0.0,0.0,0,0.0,0.0,0.000000,0.000000,0.005735,...,0.000000,0.008403,0.0,0.000000,0.001681,0.0,0.000000,0.000000,0.008403,0.0
4,251123,0.0,0.0,0.0,0,0.0,0.0,0.000000,0.000000,0.456549,...,0.000000,0.204918,0.0,0.000000,0.049180,0.0,0.008197,0.057377,0.180328,0.0

In [17]:
Std = df_num.std()
Mean = df_num.mean()
df_num = (df_num - Mean)/Std

In [18]:
df_num.describe()

,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,punctuations_per_action,number_of_words_per_action,avgCompletion,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
count,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,...,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05,4.888770e+05
mean,-9.418105e-17,-3.295374e-15,3.666243e-15,7.113034e-15,-2.521574e-16,-9.279987e-15,2.392272e-15,4.343597e-15,5.851335e-14,9.872523e-14,...,4.216185e-14,-8.204251e-14,6.536793e-15,-1.558692e-14,8.768067e-14,-3.645395e-15,1.758861e-14,1.390724e-14,-6.410091e-15,-9.870548e-16
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-1.732091e+00,-3.332267e-02,-4.257077e-01,-4.355915e-01,-2.404940e-01,-2.268127e-02,-4.815076e-02,-8.025581e-02,-2.766381e-01,-1.744404e+00,...,-9.459493e-02,-4.309335e-01,-6.572489e-02,-3.522254e-01,-3.828987e-01,-1.693876e-01,-3.519645e-01,-3.327462e-01,-3.154612e-01,-1.677878e-01
25%,-8.661986e-01,-3.332267e-02,-4.257077e-01,-4.355915e-01,-2.404940e-01,-2.268127e-02,-4.815076e-02,-8.025581e-02,-2.766381e-01,-7.260816e-01,...,-9.459493e-02,-3.870111e-01,-6.572489e-02,-3.522254e-01,-3.699382e-01,-1.693876e-01,-3.519645e-01,-3.327462e-01,-3.154612e-01,-1.677878e-01
50%,-2.932362e-04,-3.332267e-02,-4.257077e-01,-4.355915e-01,-2.404940e-01,-2.268127e-02,-4.815076e-02,-8.025581e-02,-2.766381e-01,-6.057618e-02,...,-9.459493e-02,-2.949087e-01,-6.572489e-02,-3.334269e-01,-2.920873e-01,-1.693876e-01,-3.225706e-01,-3.005268e-01,-2.838458e-01,-1.677878e-01
75%,8.661860e-01,-2.982938e-02,-4.257077e-01,-4.355915e-01,-2.404940e-01,-2.268127e-02,-4.815076e-02,-8.025581e-02,-4.472669e-02,6.084163e-01,...,-4.420256e-02,-2.930169e-02,-6.572489e-02,-6.799223e-02,-4.525877e-02,-1.693876e-01,-6.089662e-02,-7.025862e-02,-7.167649e-02,1.415585e-02
max,1.731989e+00,3.627638e+02,4.474247e+00,3.887373e+00,2.026234e+02,1.909009e+02,1.471449e+02,1.712314e+02,4.053308e+02,3.368876e+00,...,3.512802e+02,8.314479e+01,2.681486e+02,8.113625e+01,1.069233e+02,1.009481e+02,6.896033e+01,9.940940e+01,1.095385e+02,3.985711e+01

### Combining the Categorical and Numeric parts

In [19]:
df_comb = pd.concat([df_cat, df_num], axis=1)
df_comb.head()

,gender,age_group,tier_1,tier_2,tier_3,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
0,1,1,0,1,0,-0.041152,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,-0.210993,-0.065725,-0.154841,-0.239871,-0.169388,-0.351964,0.054423,-0.249069,-0.167788
1,0,2,0,1,0,0.852156,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.047619,-0.328942,-0.065725,-0.292006,-0.276234,-0.169388,-0.141475,-0.332746,-0.247943,-0.083775
2,1,1,0,1,0,-1.363061,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,-0.428837,-0.065725,-0.352225,-0.379711,-0.169388,-0.345046,-0.332746,-0.315461,-0.167788
3,1,1,0,1,0,0.006454,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,-0.422631,-0.065725,-0.352225,-0.373283,-0.169388,-0.351964,-0.332746,-0.298724,-0.167788
4,0,1,0,1,0,-0.130624,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,-0.205561,-0.065725,-0.352225,-0.101532,-0.169388,-0.331606,-0.205805,0.043711,-0.167788

### Shuffling the data:

In [20]:
df_shuffled = df_comb.iloc[np.random.permutation(range(len(df_comb)))]

In [21]:
df_shuffled.reset_index(drop=True, inplace=True)
df_shuffled.head()

,gender,age_group,tier_1,tier_2,tier_3,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
0,1,1,0,1,0,-0.073536,-0.033323,-0.425708,-0.435591,0.734813,...,-0.094595,-0.422785,-0.065725,-0.352225,-0.373442,-0.169388,-0.351964,-0.332746,-0.299000,-0.167788
1,0,3,0,1,0,1.135502,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.049159,-0.395697,-0.065725,-0.352225,-0.326625,-0.169388,-0.229811,-0.332746,-0.315461,0.007367
2,1,1,0,1,0,0.591047,0.050780,0.799281,1.725891,-0.240494,...,-0.094595,0.401748,-0.065725,-0.352225,0.782915,-0.169388,0.772766,-0.332746,0.811958,-0.105669
3,1,1,0,1,0,-0.588566,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,-0.421872,-0.065725,-0.352225,-0.372497,-0.169388,-0.351964,-0.312633,-0.315461,-0.167788
4,1,1,0,1,0,-0.022167,-0.033323,-0.425708,-0.435591,-0.240494,...,-0.094595,0.101977,-0.065725,-0.352225,0.179678,-0.169388,-0.351964,-0.332746,0.663827,-0.167788

### Separating the output:

In [22]:
df_y = df_shuffled[["age_group"]]

In [23]:
df_shuffled.drop(["age_group"], axis=1, inplace= True)

C:\Users\Admin\anaconda3.2020\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [24]:
df_shuffled.head()

,gender,tier_1,tier_2,tier_3,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
0,1,0,1,0,-0.073536,-0.033323,-0.425708,-0.435591,0.734813,-0.022681,...,-0.094595,-0.422785,-0.065725,-0.352225,-0.373442,-0.169388,-0.351964,-0.332746,-0.299000,-0.167788
1,0,0,1,0,1.135502,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.049159,-0.395697,-0.065725,-0.352225,-0.326625,-0.169388,-0.229811,-0.332746,-0.315461,0.007367
2,1,0,1,0,0.591047,0.050780,0.799281,1.725891,-0.240494,-0.022681,...,-0.094595,0.401748,-0.065725,-0.352225,0.782915,-0.169388,0.772766,-0.332746,0.811958,-0.105669
3,1,0,1,0,-0.588566,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.094595,-0.421872,-0.065725,-0.352225,-0.372497,-0.169388,-0.351964,-0.312633,-0.315461,-0.167788
4,1,0,1,0,-0.022167,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.094595,0.101977,-0.065725,-0.352225,0.179678,-0.169388,-0.351964,-0.332746,0.663827,-0.167788

In [25]:
df_y.head()

   age_group
0          1
1          3
2          1
3          1
4          1

#### Current relevant variables in memory:

Dataframes:
- df --> untouched dataset
- df_comb --> normalized dataset 
- df_shuffled --> shuffled dataset
- df_y --> output

Transformation:
- Std --> standard deviation of dataset
- Mean --> mean of dataset

### Converting data into numpy arrays and splitting into training and validation sets:

In [26]:
X = df_shuffled.to_numpy()
y = pd.get_dummies(df_y["age_group"]).to_numpy()

In [27]:
X.shape, y.shape

((488877, 27), (488877, 4))

In [28]:
X[0], y[:4]

(array([ 1.00000000e+00,  0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        -7.35356083e-02, -3.33226724e-02, -4.25707733e-01, -4.35591495e-01,
         7.34813179e-01, -2.26812673e-02,  7.35483841e+01, -8.02558057e-02,
         4.95457304e-01, -1.62254275e+00, -1.90951106e-03,  5.14399044e-01,
        -4.19517000e-02, -9.45949291e-02, -4.22784694e-01, -6.57248890e-02,
        -3.52225352e-01, -3.73442308e-01, -1.69387616e-01, -3.51964464e-01,
        -3.32746161e-01, -2.99000282e-01, -1.67787828e-01]),
 array([[1, 0, 0, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0]], dtype=uint8))

In [29]:
# Keeping 40,000 examples in validation set and remaining in training set
X_train = X[:-40000]
X_val = X[-40000:]
y_train = y[:-40000]
y_val = y[-40000:]

In [30]:
X_train.shape, y_train.shape

((448877, 27), (448877, 4))

### Using keras to build a multi-class classifier

In [31]:
# !pip install --upgrade pip
# !pip install tensorflow

In [32]:
import tensorflow as tf
from tensorflow import keras

In [33]:
model = keras.Sequential([
    keras.layers.Dense(64, activation=tf.nn.relu, input_dim=27),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(4, activation=tf.nn.softmax)
])

In [34]:
model.compile(optimizer='sgd', loss='categorical_crossentropy',metrics=['accuracy'])

In [35]:
model.fit(X_train, y_train, epochs=20, validation_data=(X_val, y_val))

Epoch 1/20
14028/14028 [==============================] - 18s 1ms/step - loss: 0.7330 - accuracy: 0.6653 - val_loss: 0.6792 - val_accuracy: 0.6792
Epoch 2/20
14028/14028 [==============================] - 17s 1ms/step - loss: 0.6666 - accuracy: 0.6839 - val_loss: 0.6631 - val_accuracy: 0.6881
Epoch 3/20
14028/14028 [==============================] - 16s 1ms/step - loss: 0.6574 - accuracy: 0.6880 - val_loss: 0.6590 - val_accuracy: 0.6889
Epoch 4/20
14028/14028 [==============================] - 17s 1ms/step - loss: 0.6527 - accuracy: 0.6896 - val_loss: 0.6536 - val_accuracy: 0.6908
Epoch 5/20
14028/14028 [==============================] - 18s 1ms/step - loss: 0.6488 - accuracy: 0.6913 - val_loss: 0.6505 - val_accuracy: 0.6906
Epoch 6/20
14028/14028 [==============================] - 17s 1ms/step - loss: 0.6462 - accuracy: 0.6923 - val_loss: 0.6457 - val_accuracy: 0.6920
Epoch 7/20
14028/14028 [==============================] - 15s 1ms/step - loss: 0.6430 - accuracy: 0.6939 - val_loss: 0.6464 - val_accuracy: 0.6923
Epoch 8/20
14028/14028 [==============================] - 16s 1ms/step - loss: 0.6413 - accuracy: 0.6953 - val_loss: 0.6436 - val_accuracy: 0.6950
Epoch 9/20
14028/14028 [==============================] - 15s 1ms/step - loss: 0.6387 - accuracy: 0.6957 - val_loss: 0.6409 - val_accuracy: 0.6949
Epoch 10/20
14028/14028 [==============================] - 16s 1ms/step - loss: 0.6368 - accuracy: 0.6972 - val_loss: 0.6392 - val_accuracy: 0.6975
Epoch 11/20
14028/14028 [==============================] - 16s 1ms/step - loss: 0.6351 - accuracy: 0.6974 - val_loss: 0.6390 - val_accuracy: 0.6949
Epoch 12/20
14028/14028 [==============================] - 17s 1ms/step - loss: 0.6332 - accuracy: 0.6978 - val_loss: 0.6344 - val_accuracy: 0.6987
Epoch 13/20
14028/14028 [==============================] - 18s 1ms/step - loss: 0.6320 - accuracy: 0.6990 - val_loss: 0.6335 - val_accuracy: 0.6972
Epoch 14/20
14028/14028 [==============================] - 17s 1ms/step - loss: 0.6306 - accuracy: 0.6998 - val_loss: 0.6345 - val_accuracy: 0.6989
Epoch 15/20
14028/14028 [==============================] - 16s 1ms/step - loss: 0.6297 - accuracy: 0.7001 - val_loss: 0.6319 - val_accuracy: 0.6976
Epoch 16/20
14028/14028 [==============================] - 16s 1ms/step - loss: 0.6286 - accuracy: 0.7007 - val_loss: 0.6298 - val_accuracy: 0.6995
Epoch 17/20
14028/14028 [==============================] - 17s 1ms/step - loss: 0.6274 - accuracy: 0.7014 - val_loss: 0.6295 - val_accuracy: 0.7010
Epoch 18/20
14028/14028 [==============================] - 16s 1ms/step - loss: 0.6264 - accuracy: 0.7018 - val_loss: 0.6321 - val_accuracy: 0.6984
Epoch 19/20
14028/14028 [==============================] - 15s 1ms/step - loss: 0.6258 - accuracy: 0.7020 - val_loss: 0.6286 - val_accuracy: 0.6999
Epoch 20/20
14028/14028 [==============================] - 17s 1ms/step - loss: 0.6247 - accuracy: 0.7023 - val_loss: 0.6277 - val_accuracy: 0.7002

### Making Predictions on Validation set and evaluating it

In [36]:
import sklearn
from sklearn import metrics

In [37]:
y_val_pred = model.predict(X_val)
y_val_pred.shape

(40000, 4)

In [38]:
for i in range(y_val.shape[0]):
    y_val_pred[i,:] = (y_val_pred[i,:] == max(y_val_pred[i,:]))
val_predict = y_val_pred @ np.array([1,2,3,4]).reshape(4,1)
y_val = y_val @ np.array([1,2,3,4]).reshape(4,1)

In [39]:
print(metrics.classification_report(y_val, val_predict, digits=4))

              precision    recall  f1-score   support

           1     0.8823    0.8744    0.8783     25360
           2     0.4080    0.5225    0.4582      4815
           3     0.3288    0.2453    0.2810      4904
           4     0.4195    0.4298    0.4246      4921

    accuracy                         0.7002     40000
   macro avg     0.5097    0.5180    0.5105     40000
weighted avg     0.7004    0.7002    0.6987     40000

### Preparing test set for prediction

In [40]:
df_test = pd.read_csv("data/test_age_dataset.csv")
df_test.head()

,Unnamed: 0,userId,tier,gender,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
0,62683,33840667,2,1,0.000000,0.0,0.0,0,0.0,0.0,...,0.000000,0.062992,0.0,0.000000,0.012598,0.000000,0.000000,0.062992,0.000000,0.0
1,173104,1828421,2,1,0.001818,0.0,0.0,0,0.0,0.0,...,0.000000,0.003636,0.0,0.000000,0.000727,0.000000,0.000000,0.003636,0.000000,0.0
2,306061,57353310,2,1,0.000000,0.0,0.0,0,0.0,0.0,...,0.000000,1.028571,0.0,0.000000,0.211429,0.000000,0.000000,0.742857,0.314286,0.0
3,422061,36618563,2,2,0.000000,0.0,0.0,4,0.0,0.0,...,0.007937,0.166667,0.0,0.067460,0.006349,0.000000,0.111111,0.023810,0.031746,201.0
4,219653,39484434,2,1,0.000000,0.0,0.0,0,0.0,0.0,...,0.000000,0.233871,0.0,0.116935,0.000000,0.233871,0.000000,0.000000,0.000000,0.0

In [41]:
df_test.drop(["userId"], axis=1, inplace= True)

In [42]:
df_test.shape

(54320, 25)

### Dealing with categorical variables:

In [43]:
df_test_cat = df_test[["gender", "tier"]]

In [44]:
df_test_cat['gender'] = df_test_cat['gender'].map({1:1, 2:0}).astype('uint8')

C:\Users\Admin\anaconda3.2020\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [45]:
df_test_cat["tier"].value_counts()

2    44192
1     5713
3     4415
Name: tier, dtype: int64

In [46]:
df3 = pd.get_dummies(df_test_cat["tier"])
df3.columns = ["tier_1","tier_2","tier_3"]
df3.head()

   tier_1  tier_2  tier_3
0       0       1       0
1       0       1       0
2       0       1       0
3       0       1       0
4       0       1       0

In [47]:
df_test_cat = pd.concat([df_test_cat.drop(["tier"], axis=1),df3], axis=1)

In [48]:
df_test_cat.head()

   gender  tier_1  tier_2  tier_3
0       1       0       1       0
1       1       0       1       0
2       1       0       1       0
3       0       0       1       0
4       1       0       1       0

### Dealing with numeric variables:

In [49]:
df_test_num = df_test.drop(["tier","gender"], axis=1)
df_test_num.head()

,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,punctuations_per_action,number_of_words_per_action,avgCompletion,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
0,62683,0.000000,0.0,0.0,0,0.0,0.0,0.0,0.000000,0.033242,...,0.000000,0.062992,0.0,0.000000,0.012598,0.000000,0.000000,0.062992,0.000000,0.0
1,173104,0.001818,0.0,0.0,0,0.0,0.0,0.0,0.000000,0.051057,...,0.000000,0.003636,0.0,0.000000,0.000727,0.000000,0.000000,0.003636,0.000000,0.0
2,306061,0.000000,0.0,0.0,0,0.0,0.0,0.0,0.000000,0.190984,...,0.000000,1.028571,0.0,0.000000,0.211429,0.000000,0.000000,0.742857,0.314286,0.0
3,422061,0.000000,0.0,0.0,4,0.0,0.0,0.0,0.130435,0.460543,...,0.007937,0.166667,0.0,0.067460,0.006349,0.000000,0.111111,0.023810,0.031746,201.0
4,219653,0.000000,0.0,0.0,0,0.0,0.0,0.0,0.000000,0.205251,...,0.000000,0.233871,0.0,0.116935,0.000000,0.233871,0.000000,0.000000,0.000000,0.0

In [50]:
df_test_num = (df_test_num - Mean)/Std

In [51]:
df_test_num.describe()

,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,emoji_count_per_action,punctuations_per_action,number_of_words_per_action,avgCompletion,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
count,54320.000000,54320.000000,54320.000000,54320.000000,54320.000000,54320.000000,54320.000000,54320.000000,54320.000000,54320.000000,...,54320.000000,54320.000000,54320.000000,54320.000000,54320.000000,54320.000000,54320.000000,54320.000000,54320.000000,54320.000000
mean,-0.000509,-0.000417,-0.004272,-0.006070,-0.001611,0.006549,-0.003559,-0.004311,-0.000986,0.003853,...,0.003620,0.002641,0.004070,0.004969,0.002381,-0.000036,0.000195,0.005195,0.003503,-0.006599
std,0.999976,1.257488,0.996016,0.992107,0.917700,1.270690,0.856478,0.818385,0.927334,1.005844,...,0.867076,1.026769,1.018808,1.005233,1.028019,0.907312,0.984569,1.065505,1.000891,0.937089
min,-1.732059,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,-0.048151,-0.080256,-0.276638,-1.744534,...,-0.094595,-0.430950,-0.065725,-0.352225,-0.382899,-0.169388,-0.351964,-0.332746,-0.315461,-0.167788
25%,-0.864666,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,-0.048151,-0.080256,-0.276638,-0.725607,...,-0.094595,-0.386828,-0.065725,-0.352225,-0.370066,-0.169388,-0.351964,-0.332746,-0.315461,-0.167788
50%,0.002028,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,-0.048151,-0.080256,-0.276638,-0.060434,...,-0.094595,-0.293838,-0.065725,-0.333427,-0.292565,-0.169388,-0.323083,-0.300682,-0.283846,-0.167788
75%,0.863691,-0.029829,-0.425708,-0.435591,-0.240494,-0.022681,-0.048151,-0.080256,-0.049488,0.610412,...,-0.044657,-0.029367,-0.065725,-0.067992,-0.049167,-0.169388,-0.059755,-0.072464,-0.066490,0.014204
max,1.731906,277.656497,4.474247,3.887373,42.022816,190.900903,82.983837,78.263505,101.331123,3.368876,...,93.669384,37.158027,149.635724,41.799353,49.234825,63.967027,42.022810,53.035640,43.696299,28.828806

### Combining the Categorical and Numeric parts

In [52]:
df_test_comb = pd.concat([df_test_cat, df_test_num], axis=1)
df_test_comb.head()

,gender,tier_1,tier_2,tier_3,Unnamed: 0,following_rate,followers_avg_age,following_avg_age,max_repetitive_punc,num_of_hashtags_per_action,...,creations,content_views,num_of_comments,weekends_trails_watched_per_day,weekdays_trails_watched_per_day,slot1_trails_watched_per_day,slot2_trails_watched_per_day,slot3_trails_watched_per_day,slot4_trails_watched_per_day,avgt2
0,1,0,1,0,-1.332348,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.094595,-0.362332,-0.065725,-0.352225,-0.310822,-0.169388,-0.351964,-0.193383,-0.315461,-0.167788
1,1,0,1,0,-0.628169,-0.032586,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.094595,-0.427897,-0.065725,-0.352225,-0.378738,-0.169388,-0.351964,-0.324701,-0.315461,-0.167788
2,1,0,1,0,0.219727,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.094595,0.704248,-0.065725,-0.352225,0.826710,-0.169388,-0.351964,1.310747,0.310525,-0.167788
3,0,0,1,0,0.959485,-0.033323,-0.425708,-0.435591,1.059916,-0.022681,...,-0.050602,-0.247813,-0.065725,-0.032651,-0.346574,-0.169388,-0.075989,-0.280070,-0.252230,0.036899
4,1,0,1,0,-0.331316,-0.033323,-0.425708,-0.435591,-0.240494,-0.022681,...,-0.094595,-0.173579,-0.065725,0.201724,-0.382899,1.036372,-0.351964,-0.332746,-0.315461,-0.167788

In [53]:
X_test = df_test_comb.to_numpy()
X_test.shape

(54320, 27)

### Making predictions on Test Set

In [54]:
y_pred = model.predict(X_test)
y_pred.shape

(54320, 4)

In [55]:
for i in range(y_pred.shape[0]):
    y_pred[i,:] = (y_pred[i,:] == max(y_pred[i,:]))
predictions = y_pred @ np.array([1,2,3,4]).reshape(4,1)

In [56]:
predictions

array([[1.],
       [1.],
       [1.],
       ...,
       [4.],
       [1.],
       [1.]])

In [57]:
df_pred = pd.DataFrame(
    {"prediction" : predictions.reshape(-1)}
    )

In [58]:
df_pred.shape

(54320, 1)

In [59]:
df_pred.to_csv('predictions/vibe_bruv.csv', index = False)